version: '3.8'
services:
  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: rust
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    depends_on:
      - database
    environment:
      DATABASE_URL: mysql://root@127.0.0.1:3306/rust
    ports:
      - "8080:8080"

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
      